### ISSUE TITLE
Scenario for login and logout

### ISSUE THREAD

**Issue by binarykitchen** [matt-downs/neto-api-node#8]
This is probably more a general question rather than a bug report. I do not see how the login and logout would work using your API. This for a custom-built frontend using your package. And neto itself as the backend.

How to validate username and password for example.

Thanks!

**Comment by matt-downs** [comment]
Hi @binarykitchen! 

At this stage, this library doesn't handle any login/logout logic, it assumes that you already have obtained an API key by some other means. 

The global API key for your site can be found by navigating to `Settings & tools > API Settings` on your Neto control panel. You can also generate user-specific API keys from `Settings & tools > Staff Users` which will allow you to restrict API access to certain methods using User Permission Groups.

If your app is going to be public facing, you could also [apply to be part of our OAuth authentication program](https://www.netohq.com/partners/s/integration-partner), which would allow users to sign in with their store domain and staff user credentials instead of needing to find the API key for their site.

**Comment by binarykitchen** [comment]
Great, thanks man. This helps.

Maybe worth adding a section about that in the existing README.md?

**Comment by matt-downs** [comment]
Not a bad idea! I'll actually keep the issue open for now so I don't forget to update the readme 😅

**Comment by matt-downs** [comment]
Added authentication info to readme 😁
